/**
This code is autogenerated using Capriccio 1.0.0 - https://github.com/shibapm/capriccio
DO NOT EDIT
*/

import XCTest
import XCTest_Gherkin


final class FeatureNumberOne: BaseTest {
    
    
    func testTitleBlue() {
        
        Given("I'm on the home page")
        
        Then("I see a cell named Blue")
        
    }
    
    
    
    func testTitleGreen() {
        
        Given("I'm on the home page")
        
        And("I scroll until I see a cell named Green")
        
        Then("I see a cell named Green")
        
    }
    
    
}
