/**
This code is autogenerated using Capriccio 1.0.0 - https://github.com/shibapm/capriccio
DO NOT EDIT
*/

import XCTest
import XCTest_Gherkin


final class FeatureNumberTwo: BaseTest {
    
    
    
    func testScenarioIWantToTestWithValue1AndValue2() {
        
        Given("I'm in a situation")
    
        When("something happens value1")
    
        Then("something else happens value2")
    
    }
    
    func testScenarioIWantToTestWithValue3AndValue4() {
        
        Given("I'm in a situation")
    
        When("something happens value3")
    
        Then("something else happens value4")
    
    }
    
    
    
}
